import mongoose from "mongoose";

const aboutSchema = new mongoose.Schema({
    banner:{
        type:String,
        required:true
    },
    bannerAlt:{
        type:String,
    },
    metaTitle:{
        type:String,
        required:true
    },
    metaDescription:{
        type:String,
        required:true
    },
    pageTitle:{
        type:String,
        required:true
    },
    firstSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        imageAlt:{
            type:String,
        }
    },
    secondSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        mission:{
            logoAlt:{
                type:String,
            },
            logo:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        },
        vision:{
            logoAlt:{
                type:String,
            },
            logo:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        },
        values:{
            logoAlt:{
                type:String,
            },
            logo:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }
    },
    thirdSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        chairman:{
            imageAlt:{
                type:String,
            },
            image:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            },
            name:{
                type:String,
                required:true
            }
        },
        ceo:{
            imageAlt:{
                type:String,
            },
            image:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            },
            name:{
                type:String,
                required:true
            }
        }
    },
    certifications:[{
        imageAlt:{
            type:String,
        },
        image:{
            type:String,
            required:true
        },
        title:{
            type:String,
            required:true
        }
    }]
})

export default mongoose.models.About || mongoose.model("About", aboutSchema);