import mongoose from "mongoose";

const commitmentSchema = new mongoose.Schema({
    banner:{
        type:String,
        required:true
    },
    bannerAlt:{
        type:String,
        required:true
    },
    firstSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            title:{
                type:String,
                required:true
            },
            logo:{
                type:String,
                required:true
            },
            logoAlt:{
                type:String,
            }
        }]
    },
    secondSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            },
            logo:{
                type:String,
                required:true
            },
            logoAlt:{
                type:String,
            }
        }]
    },
    thirdSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            },
            image:{
                type:String,
                required:true
            },
            imageAlt:{
                type:String,
            }
        }]
    },
    metaTitle:{
        type:String,
    },
    metaDescription:{
        type:String,
    }
})

export default mongoose.models.Commitment || mongoose.model("Commitment", commitmentSchema);