import { certifications } from "@/app/components/about/data";
import mongoose from "mongoose";

const HomeSchema = new mongoose.Schema({
    metaTitle:{
        type:String,
    },
    metaDescription:{
        type:String,
    },
    banners:[{
        image:{
            type:String,
        },
        imageAlt:{
            type:String,
        },
        title:{
            type:String,
        }
    }],
    aboutSection:{
        title:{
            type:String,
        },
        description:{
            type:String,
        },
        image:{
            type:String,
        },
        items:[{
            number:{
                type:String,
            },
            value:{
                type:String,
            }
        }]
    },
    partners:{
        title:{
            type:String,
        },
        items:[{
            image:{
                type:String,
            },
            imageAlt:{
                type:String,
            }
        }]
    },
    services:{
        title:{
            type:String,
        },
        items:[{
            image:{
                type:String,
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
            },
            description:{
                type:String,
            },
            url:{
                type:String,
            }
        }]
    },
    systems:{
        title:{
            type:String,
        },
        items:[{
            image:{
                type:String,
            },
            imageAlt:{
                type:String,
            },
            title:{
                type:String,
            }
        }]
    },
    certifications:{
        title:{
            type:String,
        },
        items:[{
            image:{
                type:String,
            },
            imageAlt:{
                type:String,
            }
        }]
    },
    projects:{
        title:{
            type:String,
        },
        description:{
            type:String,
        }
    },
    socials:{
        title:{
            type:String,
        },
        email:{
            type:String,
        },
        phone:{
            type:String,
        },
        items:[{
            title:{
                type:String,
            },
            link:{
                type:String,
            }
        }]
    }
})

export default mongoose.models.Home || mongoose.model("Home", HomeSchema);