import type { Metadata } from "next";
import { Host_Grotesk} from "next/font/google";
import "../../app/globals.css";
import Header from "../components/common/Header";

const hostGrostek = Host_Grotesk({
  variable: "--font-host-grotesk",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hostGrostek.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
